services:
  
  node1:
    build:
      context: .
      dockerfile: docker/Dockerfile
      
    container_name: node1
    
    ports:
      - "8001:25000/udp"
      - "5001:10000/tcp"
    
    environment:
      - HOST=${HOST:-0}
      - API_PORT=5001
      - NODE_PORT=25000
      - IP=${NIP:-0}
      - OUTSIDE_IP=${NIP:-0}
      - OUTSIDE_PORT=8001
      
    restart: "no"

      
  node2:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: node2
    ports:
      - "8002:25000/udp"
      - "5002:10000/tcp"
    environment:
      - HOST=${HOST:-0}
      - API_PORT=5002
      - NODE_PORT=25000
      - IP=${NIP:-0}
      - OUTSIDE_IP=${NIP:-0}
      - OUTSIDE_PORT=8002
      
    restart: "no"
      
      
  node3:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: node3
    ports:
      - "8003:25000/udp"
      - "5003:10000/tcp"
    environment:
      - HOST=${HOST:-0}
      - API_PORT=5003
      - NODE_PORT=25000
      - IP=${NIP:-0}
      - OUTSIDE_IP=${NIP:-0}
      - OUTSIDE_PORT=8003
      
    restart: "no"
    
  node4:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: node4
    ports:
      - "8004:25000/udp"
      - "5004:10000/tcp"
    environment:
      - HOST=${HOST:-0}
      - API_PORT=5004  
      - NODE_PORT=25000
      - OUTSIDE_IP=${NIP:-0}
      - OUTSIDE_PORT=8004
      
    restart: "no"
      
networks:
  default:
    driver: bridge
    